### ISSUE TITLE
Login/Registration Page

### ISSUE THREAD

**Issue by FxPouya** [thantmyat31/react-native-blog#1]
Hello,
Login/Registration page doesn't work?
Should I complete this section?
Regards,

**Comment by thantmyat31** [comment]
Hi Friend,
Thanks a lot for your interesting.
I just left this repo for the moment, since I'm working on another repo for now.
Actually, not only login /registration section, on other screens also need to update.
I will complete then this repo a little bit later.

Hope you may understand,
